### ISSUE TITLE
Question about the delays

### ISSUE THREAD

**Issue by Gershon123** [SawFowl/GuiShopManager#6]
I noticed the plugin uses 5 tick delays for switching between the menus. Is there a reason this is necessary?

**Comment by SawFowl** [comment]
Yes. There were some bugs caused by a player's ping. As a protection against them was made such a delay.

**Comment by Gershon123** [comment]
Can you elaborate on which sort of bugs and how to reproduce them?

I cloned the project and wasn't able to notice any bugs when I removed the delays

**Comment by SawFowl** [comment]
As a rule, it was a visual dupe of items. The bug did not appear for everyone. I could not figure out the exact cause of the bug, but found that creating a small delay eliminates it.
Of course you can change the code as you like. I suspect the bug was on one version of Sponge, but I didn't go through the versions.

**Comment by Gershon123** [comment]
Sounds good thanks for the info
